controllers:
    resource: ../../src/Controller/
    type: annotation

controllers_web:
    resource: ../../src/Controller/Api
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
